### PR TITLE
Feature/1513

### PR DESCRIPTION
**Pull request by medullaskyline**
Django admin changes to enable superuser to delete service accounts on request. That is, as David described it:
“Program removing service account manually upon request” is the NCI saying “David Pot is a very bad person, remove him NOW manually (with the program you have) from the ACL BEFORE the updated whitelist comes.”

### CODE REVIEW

**Comment by phyllers** [comment]
This looks like it's allowing us to deactivate the service account from the django admin site, but does it also remove the service account from the google group acl? Or is that, then, handled by the 15min cron sweeper?

**Comment by medullaskyline** [comment]
We already have the ability to manually remove a service account email from google groups ACLs through the google apps admin console (admin.google.com) and all those actions are already being logged daily. So there's no extra functionality we need to add there.

Kalle just pointed out that I may have misunderstood this issue. He said this might be something that NCI needs to be able to do or at least someone outside of ISB. David can probably clarify.

**Comment by phyllers** [comment]
No, I think you understood it correctly. I think I was expecting too much. Looks like we just need to remember to do both steps manually: 1) remove the service account from the ACL google group *and* 2) set the service account to inactive in the django admin site.

**Comment by medullaskyline** [comment]
@phyllers Is it okay to merge this now? This is the part that actually adds the django admin functionality. The feature/1513 branch in ISB-CGC-Webapp just made it look nicer. :)

**Pull request merged**
